version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'rigemdb'
      MYSQL_USER: 'geits'
      MYSQL_PASSWORD: 'denver16'
      MYSQL_ROOT_PASSWORD: 'denver16'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./my-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db  
volumes:
  my-db: