version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'rigemdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'avbravo'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'denver16'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'denver16'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./my-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
# Names our volume
volumes:
  my-db: